### ISSUE TITLE
GitHub Branches - What public branches should be included on GitHub?

### ISSUE THREAD

**Issue by KarlHanEdn** [CMPUT301W22T35/QRcode-Quest#37]
According to the Gitflow Workflow model, we could have branches for

Main
Develop
Release
Hotfix(es)
Member(s)
Feature(s)

We want a subset of these types of branches that covers our needs for this repository, which ones should be included?
In Thursday meeting today it's settled that at least the main branch and the member branches will be in the repo. For now we can work with this simplified branching model, but in case anyone feels there are problems in this model that requires adding different types of branches into the project, it can be posted here (I will probably close this thread after mid-point if nothing has been posted by then).

**Comment by KarlHanEdn** [comment]
(This is a repost of the issue, so this is Jayden's reply copied:)
I do think having feature branches as well makes sense.
E.g. feature-maps, feature-profile.
Obviously created as a feature is completed.

**Comment by KarlHanEdn** [comment]
Yeah we can do that.

**Comment by KarlHanEdn** [comment]
I thought about this after I pushed to feature branch yesterday. Should we do pull requests on the feature branches as well as the main branch?

**Comment by RottenFishbone** [comment]
I think just the main branch, personally.

**Comment by RottenFishbone** [comment]
Seems to be resolved.
