### ISSUE TITLE
Database - Retrieving different types of data from the database

### ISSUE THREAD

**Issue by KarlHanEdn** [CMPUT301W22T35/QRcode-Quest#47]
About the Result class in the database, I'm thinking about an implementation like this:
```
public class ManagerResult {
    public interface OnResult<ResultType, DocumentType> {
        ResultType retrieveResultFrom(DocumentType document);

        void onResult(ResultType result);
    }


    public abstract static class OnPlayerAccountResult implements OnResult<Result<PlayerAccount>, DocumentSnapshot> {
        public Result<PlayerAccount> retrieveResultFrom(DocumentSnapshot document) {
            assert document != null;
            // not an error when result does not exist
            if (!document.exists())
                return new Result<PlayerAccount>((PlayerAccount) null);
            String name = document.getString(Schema.PLAYER_NAME);
            String email = document.getString(Schema.PLAYER_EMAIL);
            String phone = document.getString(Schema.PLAYER_PHONE);
            if (name == null || email == null || phone == null) {
                DbError error = new DbError("Player's account contains null field on attributes " +
                        "playerName, email or phone in the database!", document);
                return new Result<PlayerAccount>(error);
            }
            PlayerAccount account = new PlayerAccount(name, email, phone);
            return new Result<PlayerAccount>(account);
        }

        @Override
        public abstract void onResult(Result<PlayerAccount> result);
    }
}
```
When we want to add method to query a new type of class from the database documents (I write OnPlayerAccountResult as an example for reading a PlayerAccount object from a single document), we add an abstract class above that implements OnResult but leaves onResult callback an abstract method. Then when we call the database we provide an implementation of the OnPlayerAccountResult class. The database manager class can use the retrieveResultFrom method to get a result object from the database document(s) and then the onResult method to decide what to do with the result object

@RottenFishbone Is this the way you are referring to about handling Result objects, or do you have another idea that may be simpler? Should we use this callback interface?

**Comment by RottenFishbone** [comment]
Took me a minute to fathom what is going on here haha. I think this is actually really smart, assuming I'm understanding it correctly.

I was trying to come up with a way neatly parse the Document into its correct type and I think this provides a way cleaner abstraction than anything I had.

**Comment by KarlHanEdn** [comment]
Cool, I will work on feature-database branch with this implementation then. 

(FYI for people looking at this thread, the getter methods will probably look something like getPlayerAccountByName(String playerName, OnPlayerAccountResult). We implement OnPlayerAccountResult.onResult callback on the caller side then pass it to the database manager.)
